spin_manifest_version = 2

[application]
authors = ["david <mallond@w3point0.com>"]
description = "Zip Code Lat Long Lookup"
name = "zip-code-embedded"
version = "0.1.0"

[[trigger.http]]
route = "/zip"
component = "zip-code-embedded"

[component.zip-code-embedded]
source = "target/zip-code-embedded.wasm"
exclude_files = ["**/node_modules"]
[component.zip-code-embedded.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
